spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    url: jdbc:mariadb://localhost:3306/policyInfo
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

devtools:
  livereload:
    enabled: true

